version: '3.1'
services:
  # سيرفر قاعدة البيانات (المخزن)
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_password # غير كلمة السر دي لزيادة الأمان
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  # سيرفر أوودو (السيستم)
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password # لازم تكون نفس كلمة سر قاعدة البيانات فوق
    volumes:
      - odoo-web-data:/var/lib/odoo
      # السطر اللي جاي ده مهم لو هتحط موديولات مدرسة خارجية (اختياري حالياً)
      # - ./addons:/mnt/extra-addons

volumes:
  odoo-db-data:
  odoo-web-data:
